-- ============================================================================
-- FUNDA PROPERTY TRACKER - COMPLETE SCHEMA
-- ============================================================================

-- Drop existing tables (WARNING: This deletes all data!)
DROP TABLE IF EXISTS properties CASCADE;
DROP TABLE IF EXISTS search_configs CASCADE;

-- ============================================================================
-- 1. SEARCH CONFIGURATIONS TABLE
-- ============================================================================
CREATE TABLE search_configs (
  id bigint generated by default as identity primary key,
  city text not null,
  neighborhoods text[] default '{}',
  price_min int default 0,
  price_max int default 1000000,
  area_min int default 0,
  max_results int default 50,
  active boolean default true,
  created_at timestamptz default now()
);

-- ============================================================================
-- 2. PROPERTIES TABLE
-- Maps to all fields from pyfunda library
-- ============================================================================
CREATE TABLE properties (
  -- Database fields
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  
  -- YOUR review fields (not from Funda)
  review_status text default 'new' check (review_status in ('new', 'reviewed', 'interested', 'rejected')),
  rating_location int check (rating_location >= 0 and rating_location <= 5),
  rating_quality int check (rating_quality >= 0 and rating_quality <= 5),
  rating_outside int check (rating_outside >= 0 and rating_outside <= 5),
  rating_value int check (rating_value >= 0 and rating_value <= 5),
  notes text,
  
  -- Identifiers (from pyfunda)
  funda_id text unique not null, -- global_id from Funda
  tiny_id text, -- alternative ID from Funda
  
  -- Address (from pyfunda)
  title text, -- e.g., "Kerkstraat 12"
  city text,
  postcode text,
  province text,
  neighbourhood text,
  municipality text,
  house_number text,
  house_number_ext text,
  
  -- Price (from pyfunda)
  price int, -- numeric price
  price_formatted text, -- formatted string like "€ 500.000 k.k."
  
  -- Property Details (from pyfunda)
  offering_type text, -- "Sale" or "Rent"
  object_type text, -- "House", "Apartment", etc.
  construction_type text,
  house_type text, -- "eengezinswoning", "appartement", etc.
  funda_status text, -- "available" or "sold" (from Funda API)
  
  -- Measurements (from pyfunda)
  living_area int, -- m²
  plot_area int, -- m²
  bedrooms int,
  rooms int,
  construction_year int,
  
  -- Energy & Features (from pyfunda)
  energy_label text,
  has_garden boolean default false,
  has_balcony boolean default false,
  has_solar_panels boolean default false,
  has_heat_pump boolean default false,
  has_roof_terrace boolean default false,
  has_parking_on_site boolean default false,
  has_parking_enclosed boolean default false,
  is_energy_efficient boolean default false,
  is_monument boolean default false,
  is_fixer_upper boolean default false,
  
  -- Listing Details (from pyfunda)
  description text,
  highlight text,
  publication_date timestamptz,
  open_house boolean default false,
  is_auction boolean default false,
  
  -- URLs (from pyfunda)
  url text not null, -- main Funda listing URL
  share_url text,
  google_maps_url text,
  brochure_url text,
  thumbnail_url text,
  
  -- Media (stored as JSONB for flexibility)
  photos jsonb default '[]', -- array of photo URLs
  features_data jsonb default '{}', -- any additional features as JSON
  
  -- Distance to train station (calculated via Google Maps)
  nearest_station_name text,
  distance_station_walk int, -- minutes (or stored as text 'N/A' if not available)
  distance_station_bike int, -- minutes (or stored as text 'N/A' if not available)
  distance_station_transit int -- minutes (or stored as text 'N/A' if not available)
);

-- ============================================================================
-- 3. INDEXES
-- ============================================================================
CREATE INDEX idx_properties_review_status ON properties(review_status);
CREATE INDEX idx_properties_city ON properties(city);
CREATE INDEX idx_properties_price ON properties(price);
CREATE INDEX idx_properties_created_at ON properties(created_at DESC);
CREATE INDEX idx_properties_station ON properties(nearest_station_name);
CREATE INDEX idx_search_configs_active ON search_configs(active);

-- ============================================================================
-- 4. AUTOMATIC UPDATED_AT TRIGGER
-- ============================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_properties_updated_at
  BEFORE UPDATE ON properties
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- 5. ROW LEVEL SECURITY (RLS)
-- ============================================================================
ALTER TABLE search_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;

-- Allow anonymous access (single user app)
CREATE POLICY "Allow anonymous full access to search_configs" 
  ON search_configs FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Allow anonymous full access to properties" 
  ON properties FOR ALL TO anon USING (true) WITH CHECK (true);

-- Allow authenticated access (for future multi-user support)
CREATE POLICY "Allow authenticated full access to search_configs" 
  ON search_configs FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated full access to properties" 
  ON properties FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============================================================================
-- 6. DISTANCE TO TRAIN STATION FIELDS
-- ============================================================================
ALTER TABLE properties
  ADD COLUMN nearest_station_name text,
  ADD COLUMN distance_station_walk int, -- minutes
  ADD COLUMN distance_station_bike int, -- minutes
  ADD COLUMN distance_station_transit int; -- minutes (by bus)

CREATE INDEX idx_properties_station ON properties(nearest_station_name);