-- 1. Create the Search Configurations table
CREATE TABLE IF NOT EXISTS search_configs (
  id bigint generated by default as identity primary key,
  city text not null,
  neighborhoods text[] default '{}',
  price_min int default 0,
  price_max int default 1000000,
  area_min int default 0,
  max_results int default 50,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Create the Properties table (if not already created)
CREATE TABLE IF NOT EXISTS properties (
  id bigint generated by default as identity primary key,
  funda_id text unique not null,
  url text not null,
  title text,
  address text,
  city text,
  price int,
  area int,
  energy_label text,
  status text default 'new', -- new, reviewed, interested, rejected
  rating_location int,
  rating_quality int,
  rating_value int,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Security (Row Level Security)
-- This ensures only logged-in users (you + gf) can see or edit data
ALTER TABLE search_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to do everything
CREATE POLICY "Allow full access to authenticated users" 
ON search_configs FOR ALL TO authenticated USING (true);

CREATE POLICY "Allow full access to authenticated users" 
ON properties FOR ALL TO authenticated USING (true);

-- 4. Initial Seed Data (So the scraper has something to run immediately)
INSERT INTO search_configs (city, neighborhoods, price_min, price_max)
VALUES ('breda', ARRAY['belcrum', 'station'], 300000, 750000);